(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage[$CommonPackage];


SingFun;



Begin["Private`"];

SetupSingFun[head_]:=Module[{MapToValues},
Values[if_head]:=if//First//Values;
Domain[if_head]:=if//First//Domain;
LeftEndpoint[if_head]:=if//First//LeftEndpoint;
RightEndpoint[if_head]:=if//First//RightEndpoint;
head/:Map[f_,g_head]:=head[f/@Values[g],Domain[g]];

Length[if_head]^:=if//Values//Length;
Points[if_head]:=Points[if//Domain,if//Length];

FastPlus[f__head]:=head[Head[{f}//First//First][Plus@@(Values/@{f}),Domain[{f}//First//First]],{f}//First//Second];

FastTimes[f__head]:=head[Head[{f}//First//First][Times@@(Values/@{f}),Domain[{f}//First//First]],(Second/@{f})//Total];

Plus[f:head[_,{a_,b_}],g:head[_,{a_,b_}]]^:=f~FastPlus~g;

Times[f_head,g_head]^:=f~FastTimes~g;
head/:Times[f_?ConstantQ,g_head]:=head[f First[g],g//Second];
head/:Times[g_head,f_?ConstantQ]:=head[First[g]f,g//Second];
head/:f_head^c_?ConstantQ:=head[First[f]^c,(f//Second) c];

MapToValues[op_]:=(op[if_head]^:=head[op[if//First],if//Second]);
MapToValues/@{Abs,Arg,Re,Im,Conjugate};

NEqual[f_head,g_head]:=Norm[Values[f-g]]<$MachineTolerance;

Dimensions[f_head]^:=f//First//Dimensions;
];

SetupSingFun[SingFun];
SingFun[if_IFun,{\[Alpha]_,\[Beta]_}][x_]:=if[x](MapToInterval[if,x]+1)^\[Alpha] (1-MapToInterval[if,x])^\[Beta];
DCT[sf_SingFun]:=DCT[First[sf]];

End[];
EndPackage[];
